# Site settings
title: Sua Park jekyll Test
email: leona910113@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, this is Sua Park's jekyll Test web pages.
  If you have any question, please let me know that.
  Connect my e-mail.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://suapark.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
